language: node_js

node_js:
  - 12

install:
  - cd docs && npm ci

script:
  - sed -i 's/^dist\/$//g' .gitignore
  - sed -i 's/^docs\/build\/$//g' .gitignore
  - npm run build
  - cd docs && npx m42kup-builder

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master